apiVersion: 1
datasources:
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    uid: alertmanager-homelab
    jsonData:
      implementation: prometheus
      handleGrafanaManagedAlerts: false
