---
- name: reload caddy
  ansible.builtin.command: docker exec {{ kuma_caddy_container_name }} caddy reload --config /etc/caddy/Caddyfile
  changed_when: true

- name: restart kuma
  community.docker.docker_compose_v2:
    project_src: "{{ kuma_compose_dir }}"
    state: present
    restarted: true
