- targets:
    - '100.101.0.7:9100'
  labels:
    job: node
    hostname: tower

- targets:
    - '100.101.0.8:9100'
  labels:
    job: node
    hostname: docker-tower

- targets:
    - '100.101.0.9:9100'
  labels:
    job: node
    hostname: mcow

- targets:
    - '100.101.0.3:9100'
  labels:
    job: node
    hostname: nether
